### ISSUE TITLE
No mechanism to set local fee at runtime

### ISSUE THREAD

**Issue by asoltys** [althea-mesh/babeld#15]
We'd like to be able to issue a command to babeld to change the local fee value at runtime and have it propagated to all of our routes. Right now it seems the only way to change the fee is through the config option or as a command line argument when babeld is started.

This is blocking further progress on creating a rita endpoint and frontend UI described here: https://forum.altheamesh.com/t/users-should-be-able-to-set-their-own-price/143

deadline:10/24/2018

**Comment by jkilpatr** [comment]
such a mechanism exists but is broken, and needs fixing.

**Comment by jkilpatr** [comment]
delayed to 10/25 by https pull.

**Comment by drozdziak1** [comment]
Fixed.
