### ISSUE TITLE
Ensure that price-aware routing is normalized based on the adjustment factor

### ISSUE THREAD

**Issue by jkilpatr** [althea-mesh/babeld#17]
Routing decisions for price aware routing should be normalized based on the adjustment factor. 

The algorithm I'm thinking of is that we have the normalized value being some value between zero and u16max / 2. Then based on the adjustment factor that value is determined (percents maybe?) then finally we normalize all prices within that by dividing by the highest known price and converting that into a percentage to apply to the range. 

I think this may have secondary effects I haven't considered, right now we can in theory apply the 500k wei/byte number by fudging the adjustment factor so that it doesn't dominate routing decisions, but we need something more consistent.

**Comment by jkilpatr** [comment]
I need to design a proper formula for this.

**Comment by jkilpatr** [comment]
ok after discussion with @asoltys  and @kingoflolz  we've decided that we can keep the existing 

selection metric = quality + multiplier * cost 

formula with the following modification 

selection metric = log_2(quality) + multiplier * log_2(cost)

while this doesn't solve the problem of any given multiplier not being appropriate for any environment it does solve the issue of dominating price/quality factors. So @drozdziak1 can go ahead and just do that for now. 

note this is log base 2 so just count the number of right shifts required to zero out the number to compute it. Very efficient with integers. 

Due 10/26/18

**Comment by kingoflolz** [comment]
@jkilpatr I think we need more precision than that in the log, as this would truncate the log to an integer, and all metrics/prices between 2^n and 2^(n+1) -1 will be the same

**Comment by jkilpatr** [comment]
due date 10/31/2018

**Comment by drozdziak1** [comment]
@kingoflolz  We could pretty easily avoid that problem by only using the log2 formula internally for choosing routes and redistributing unaltered, previously existing metrics. Then we have free reign over how we represent the numbers so floats or doubles are totally an option.

@jkilpatr Something appears wrong with the equation as both lowering price/cost (which is a **good** thing route-wise) and lowering quality (which is a **bad** thing route-wise) make the metric decrease while they should be dragging it in opposite directions.

**Comment by jkilpatr** [comment]
lower is always better for all metrics.
