### ISSUE TITLE
Ensure correcness of Price aware routing using the new log formula

### ISSUE THREAD

**Issue by jkilpatr** [althea-mesh/babeld#20]
Price aware routing should always provide the optimal route taking price into account but not in a outsized manner. 

How this will be done is to compute the result of the formula with various price, quality, and adjustment values and determine what range is provided to the user and that with the minimum and maximum adjustment factor a set of reasonable choices is offered. 

Then simulate babel in various situations with a large number of nodes (10 or more) and make sure that the paths are as expected by hand. 

https://www.wolframalpha.com/input/?i=plot+m+%3D+1+*+log2(r)+%2B+log2(p)+for+r+%3E+0+and+p+%3E+0

due: 11/1/18

**Comment by drozdziak1** [comment]
**Note:** The contour section of the Wolfram plots  is very helpful for reasoning about equivalent routes

https://www.wolframalpha.com/input/?i=contour+plot+f(d,+p)%3Dlog2(d)+%2B+log2(p)

**Comment by jkilpatr** [comment]
new metric is correct but has slow convergence problems.
